

export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";


export const SORT_PRODUCTS = "SORT_PRODUCTS";